import type { Metadata } from "next";
import "./globals.css";
import {Header} from "@/shared/ui/header/header";
import {Footer} from "@/shared/ui/footer/footer";
export const metadata: Metadata = {
  title: "DRIVERAVE",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: './favicon.ico',
    },
    shortcut: {
      url: '../public/favicon.svg'
    }
  },
  robots: {
    index: true,
    nocache: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}
